export const SET_LOADING = 'SET_LOADING'
export const SET_AUTH_DIALOG = 'SET_AUTH_DIALOG'
export const SET_USER = 'SET_USER'
export const SET_SNACKBAR = 'SET_SNACKBAR'
export const SET_MEMBERS = 'SET_MEMBERS'
export const ADD_MEMBER = 'ADD_MEMBER'